version: '2'

services:
  servidor_legal:
    image: nginx:alpine
    restart: always
    volumes:
      - /var/app/servidorlegal:/usr/share/nginx/html:ro

    ports:
      - "8006:80"
      - "8036:443"
